{ id: 'acct_18GtFBAyw96JIool',
  object: 'account',
  business_logo: null,
  business_name: null,
  business_url: null,
  charges_enabled: true,
  country: 'US',
  debit_negative_balances: false,
  decline_charge_on: { avs_failure: false, cvc_failure: false },
  default_currency: 'usd',
  details_submitted: false,
  display_name: null,
  email: 'xo.workappdemo@gmail.com',
  external_accounts:
   { object: 'list',
     data: [],
     has_more: false,
     total_count: 0,
     url: '/v1/accounts/acct_18GtFBAyw96JIool/external_accounts' },
  keys:
   { secret: 'sk_test_A97AY2s4ut75FKKVFbVVB9uB',
     publishable: 'pk_test_Wk88e4toqoKkTGVpb0c8TbxL' },
  legal_entity:
   { address:
      { city: null,
        country: 'US',
        line1: null,
        line2: null,
        postal_code: null,
        state: null },
     business_name: null,
     business_tax_id_provided: false,
     dob: { day: null, month: null, year: null },
     first_name: null,
     last_name: null,
     personal_id_number_provided: false,
     ssn_last_4_provided: false,
     type: null,
     verification:
      { details: null,
        details_code: null,
        document: null,
        status: 'unverified' } },
  managed: true,
  metadata: {},
  product_description: null,
  statement_descriptor: null,
  support_email: null,
  support_phone: null,
  timezone: 'Etc/UTC',
  tos_acceptance: { date: null, ip: null, user_agent: null },
  transfer_schedule: { delay_days: 2, interval: 'daily' },
  transfers_enabled: false,
  verification:
   { disabled_reason: 'fields_needed',
     due_by: null,
     fields_needed:
      [ 'external_account',
        'legal_entity.dob.day',
        'legal_entity.dob.month',
        'legal_entity.dob.year',
        'legal_entity.first_name',
        'legal_entity.last_name',
        'legal_entity.type',
        'tos_acceptance.date',
        'tos_acceptance.ip' ] } }
